name: PR Linting
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  lint-pr-title:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        npm install @commitlint/config-conventional
        echo "module.exports = {extends: ['@commitlint/config-conventional'], rules: {}};" > commitlint.config.js
    - name: Lint the PR Title
      run: |
        echo "${PR_TITLE}" | npx --yes commitlint
      env:
        PR_TITLE: '${{ github.event.pull_request.title }}'
